# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/
repo_url: https://github.com/MangataTS/Algorithm
site_name: Algorithm
theme:
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.top
    - toc.integrate
    - content.code.annotate 
    - toc.follow
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github-alt
  logo: logo.png
  name: material
  favicon: logo.png
  palette:
    # Toggle light mode
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
   #  favicon: attachment/portrait.png
  language: zh # 中文，解决中文搜索问题
  custom_dir: overrides
markdown_extensions: 
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Copyright &copy; power by Kaptree

extra_javascript:
  - 'javascripts/cheat.js'
  - 'javascripts/mathjax.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  #- javascripts/MathJaxTex.js
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  disqus: Algorithm

nav:
  - Home: 测试/测试程序.md
  - 语法基础: 
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 基础算法: 
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 数据结构:
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 图论:
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 数论:
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 字符串:
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 动态规划:
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 加密算法:
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 杂项:
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
  - 考研复习:
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 测试/测试程序.md
    - 考研复习/考研数据结构与算法（八）查找.md
  


