# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/
repo_url: https://github.com/Hmifree
site_name: self-improvement
theme:
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.top
    - toc.integrate
    - content.code.annotate 
    - toc.follow
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github-alt
  logo: logo.png
  name: material
  favicon: logo.png
  palette:
    # Toggle light mode
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
   #  favicon: attachment/portrait.png
  language: zh # 中文，解决中文搜索问题
  custom_dir: overrides
markdown_extensions: 
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Copyright &copy; power by Alberto 蜀ICP备2022025020号

extra_javascript:
  - 'javascripts/cheat.js'
  - 'javascripts/mathjax.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  #- javascripts/MathJaxTex.js
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  disqus: self-improvement

nav:
  - Home: index.md
  - C语言: 
    - C语言/1.初识C语言.md
    - C语言/2.分支和循环语句.md
    - C语言/3.函数.md
    - C语言/4.数组.md
    - C语言/5.操作符详解.md
    - C语言/6.结构体.md
    - C语言/7.实用调试技巧.md
    - C语言/8.数据的存储.md
    - C语言/9.指针的进阶.md
    - C语言/10.字符串和内存函数.md
    - C语言/11.自定义函数(结构体+枚举+联合).md
    - C语言/12.动态内存管理.md
    - C语言/13.程序的编译(预处理+链接).md
    - C语言/14.文件操作.md
  - 初阶数据结构:
    - 初阶数据结构/1.前言.md
    - 初阶数据结构/2.算法的时间复杂度和空间复杂度.md

